load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "ResourceNameUtilTest",
    size = "small",
    srcs = ["ResourceNameUtilTest.java"],
    deps = [
        "//java/com/tedsilb/employeemanagement:ResourceNameUtil",
        "//third_party:junit",
        "//third_party:truth",
    ],
)
