// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.tedsilb.employeemanagement;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Name)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string first = 1;</code>
     * @return The first.
     */
    java.lang.String getFirst();
    /**
     * <code>string first = 1;</code>
     * @return The bytes for first.
     */
    com.google.protobuf.ByteString
        getFirstBytes();

    /**
     * <code>string middle = 2;</code>
     * @return The middle.
     */
    java.lang.String getMiddle();
    /**
     * <code>string middle = 2;</code>
     * @return The bytes for middle.
     */
    com.google.protobuf.ByteString
        getMiddleBytes();

    /**
     * <code>string last = 3;</code>
     * @return The last.
     */
    java.lang.String getLast();
    /**
     * <code>string last = 3;</code>
     * @return The bytes for last.
     */
    com.google.protobuf.ByteString
        getLastBytes();
  }
  /**
   * Protobuf type {@code Name}
   */
  public static final class Name extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Name)
      NameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Name.newBuilder() to construct.
    private Name(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Name() {
      first_ = "";
      middle_ = "";
      last_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Name();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Name(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              first_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              middle_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              last_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tedsilb.employeemanagement.Protos.internal_static_Name_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tedsilb.employeemanagement.Protos.internal_static_Name_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tedsilb.employeemanagement.Protos.Name.class, com.tedsilb.employeemanagement.Protos.Name.Builder.class);
    }

    public static final int FIRST_FIELD_NUMBER = 1;
    private volatile java.lang.Object first_;
    /**
     * <code>string first = 1;</code>
     * @return The first.
     */
    @java.lang.Override
    public java.lang.String getFirst() {
      java.lang.Object ref = first_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        first_ = s;
        return s;
      }
    }
    /**
     * <code>string first = 1;</code>
     * @return The bytes for first.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstBytes() {
      java.lang.Object ref = first_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        first_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIDDLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object middle_;
    /**
     * <code>string middle = 2;</code>
     * @return The middle.
     */
    @java.lang.Override
    public java.lang.String getMiddle() {
      java.lang.Object ref = middle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        middle_ = s;
        return s;
      }
    }
    /**
     * <code>string middle = 2;</code>
     * @return The bytes for middle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMiddleBytes() {
      java.lang.Object ref = middle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        middle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_FIELD_NUMBER = 3;
    private volatile java.lang.Object last_;
    /**
     * <code>string last = 3;</code>
     * @return The last.
     */
    @java.lang.Override
    public java.lang.String getLast() {
      java.lang.Object ref = last_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        last_ = s;
        return s;
      }
    }
    /**
     * <code>string last = 3;</code>
     * @return The bytes for last.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastBytes() {
      java.lang.Object ref = last_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        last_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, first_);
      }
      if (!getMiddleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, middle_);
      }
      if (!getLastBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, last_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, first_);
      }
      if (!getMiddleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, middle_);
      }
      if (!getLastBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, last_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tedsilb.employeemanagement.Protos.Name)) {
        return super.equals(obj);
      }
      com.tedsilb.employeemanagement.Protos.Name other = (com.tedsilb.employeemanagement.Protos.Name) obj;

      if (!getFirst()
          .equals(other.getFirst())) return false;
      if (!getMiddle()
          .equals(other.getMiddle())) return false;
      if (!getLast()
          .equals(other.getLast())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRST_FIELD_NUMBER;
      hash = (53 * hash) + getFirst().hashCode();
      hash = (37 * hash) + MIDDLE_FIELD_NUMBER;
      hash = (53 * hash) + getMiddle().hashCode();
      hash = (37 * hash) + LAST_FIELD_NUMBER;
      hash = (53 * hash) + getLast().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tedsilb.employeemanagement.Protos.Name parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tedsilb.employeemanagement.Protos.Name prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Name}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Name)
        com.tedsilb.employeemanagement.Protos.NameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tedsilb.employeemanagement.Protos.internal_static_Name_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tedsilb.employeemanagement.Protos.internal_static_Name_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tedsilb.employeemanagement.Protos.Name.class, com.tedsilb.employeemanagement.Protos.Name.Builder.class);
      }

      // Construct using com.tedsilb.employeemanagement.Protos.Name.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        first_ = "";

        middle_ = "";

        last_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tedsilb.employeemanagement.Protos.internal_static_Name_descriptor;
      }

      @java.lang.Override
      public com.tedsilb.employeemanagement.Protos.Name getDefaultInstanceForType() {
        return com.tedsilb.employeemanagement.Protos.Name.getDefaultInstance();
      }

      @java.lang.Override
      public com.tedsilb.employeemanagement.Protos.Name build() {
        com.tedsilb.employeemanagement.Protos.Name result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tedsilb.employeemanagement.Protos.Name buildPartial() {
        com.tedsilb.employeemanagement.Protos.Name result = new com.tedsilb.employeemanagement.Protos.Name(this);
        result.first_ = first_;
        result.middle_ = middle_;
        result.last_ = last_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tedsilb.employeemanagement.Protos.Name) {
          return mergeFrom((com.tedsilb.employeemanagement.Protos.Name)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tedsilb.employeemanagement.Protos.Name other) {
        if (other == com.tedsilb.employeemanagement.Protos.Name.getDefaultInstance()) return this;
        if (!other.getFirst().isEmpty()) {
          first_ = other.first_;
          onChanged();
        }
        if (!other.getMiddle().isEmpty()) {
          middle_ = other.middle_;
          onChanged();
        }
        if (!other.getLast().isEmpty()) {
          last_ = other.last_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tedsilb.employeemanagement.Protos.Name parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tedsilb.employeemanagement.Protos.Name) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object first_ = "";
      /**
       * <code>string first = 1;</code>
       * @return The first.
       */
      public java.lang.String getFirst() {
        java.lang.Object ref = first_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          first_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first = 1;</code>
       * @return The bytes for first.
       */
      public com.google.protobuf.ByteString
          getFirstBytes() {
        java.lang.Object ref = first_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          first_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first = 1;</code>
       * @param value The first to set.
       * @return This builder for chaining.
       */
      public Builder setFirst(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        first_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirst() {
        
        first_ = getDefaultInstance().getFirst();
        onChanged();
        return this;
      }
      /**
       * <code>string first = 1;</code>
       * @param value The bytes for first to set.
       * @return This builder for chaining.
       */
      public Builder setFirstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        first_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object middle_ = "";
      /**
       * <code>string middle = 2;</code>
       * @return The middle.
       */
      public java.lang.String getMiddle() {
        java.lang.Object ref = middle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          middle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string middle = 2;</code>
       * @return The bytes for middle.
       */
      public com.google.protobuf.ByteString
          getMiddleBytes() {
        java.lang.Object ref = middle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          middle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string middle = 2;</code>
       * @param value The middle to set.
       * @return This builder for chaining.
       */
      public Builder setMiddle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        middle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string middle = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMiddle() {
        
        middle_ = getDefaultInstance().getMiddle();
        onChanged();
        return this;
      }
      /**
       * <code>string middle = 2;</code>
       * @param value The bytes for middle to set.
       * @return This builder for chaining.
       */
      public Builder setMiddleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        middle_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object last_ = "";
      /**
       * <code>string last = 3;</code>
       * @return The last.
       */
      public java.lang.String getLast() {
        java.lang.Object ref = last_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          last_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last = 3;</code>
       * @return The bytes for last.
       */
      public com.google.protobuf.ByteString
          getLastBytes() {
        java.lang.Object ref = last_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          last_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last = 3;</code>
       * @param value The last to set.
       * @return This builder for chaining.
       */
      public Builder setLast(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLast() {
        
        last_ = getDefaultInstance().getLast();
        onChanged();
        return this;
      }
      /**
       * <code>string last = 3;</code>
       * @param value The bytes for last to set.
       * @return This builder for chaining.
       */
      public Builder setLastBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        last_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Name)
    }

    // @@protoc_insertion_point(class_scope:Name)
    private static final com.tedsilb.employeemanagement.Protos.Name DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tedsilb.employeemanagement.Protos.Name();
    }

    public static com.tedsilb.employeemanagement.Protos.Name getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Name>
        PARSER = new com.google.protobuf.AbstractParser<Name>() {
      @java.lang.Override
      public Name parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Name(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Name> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Name> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tedsilb.employeemanagement.Protos.Name getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * employees/{id}, id.length 10, [A-Za-z]
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * employees/{id}, id.length 10, [A-Za-z]
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.Name name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>.Name name = 2;</code>
     * @return The name.
     */
    com.tedsilb.employeemanagement.Protos.Name getName();
    /**
     * <code>.Name name = 2;</code>
     */
    com.tedsilb.employeemanagement.Protos.NameOrBuilder getNameOrBuilder();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              com.tedsilb.employeemanagement.Protos.Name.Builder subBuilder = null;
              if (name_ != null) {
                subBuilder = name_.toBuilder();
              }
              name_ = input.readMessage(com.tedsilb.employeemanagement.Protos.Name.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(name_);
                name_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tedsilb.employeemanagement.Protos.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tedsilb.employeemanagement.Protos.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tedsilb.employeemanagement.Protos.Employee.class, com.tedsilb.employeemanagement.Protos.Employee.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * employees/{id}, id.length 10, [A-Za-z]
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * employees/{id}, id.length 10, [A-Za-z]
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private com.tedsilb.employeemanagement.Protos.Name name_;
    /**
     * <code>.Name name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return name_ != null;
    }
    /**
     * <code>.Name name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public com.tedsilb.employeemanagement.Protos.Name getName() {
      return name_ == null ? com.tedsilb.employeemanagement.Protos.Name.getDefaultInstance() : name_;
    }
    /**
     * <code>.Name name = 2;</code>
     */
    @java.lang.Override
    public com.tedsilb.employeemanagement.Protos.NameOrBuilder getNameOrBuilder() {
      return getName();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (name_ != null) {
        output.writeMessage(2, getName());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (name_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getName());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tedsilb.employeemanagement.Protos.Employee)) {
        return super.equals(obj);
      }
      com.tedsilb.employeemanagement.Protos.Employee other = (com.tedsilb.employeemanagement.Protos.Employee) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tedsilb.employeemanagement.Protos.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tedsilb.employeemanagement.Protos.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        com.tedsilb.employeemanagement.Protos.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tedsilb.employeemanagement.Protos.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tedsilb.employeemanagement.Protos.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tedsilb.employeemanagement.Protos.Employee.class, com.tedsilb.employeemanagement.Protos.Employee.Builder.class);
      }

      // Construct using com.tedsilb.employeemanagement.Protos.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        if (nameBuilder_ == null) {
          name_ = null;
        } else {
          name_ = null;
          nameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tedsilb.employeemanagement.Protos.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public com.tedsilb.employeemanagement.Protos.Employee getDefaultInstanceForType() {
        return com.tedsilb.employeemanagement.Protos.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public com.tedsilb.employeemanagement.Protos.Employee build() {
        com.tedsilb.employeemanagement.Protos.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tedsilb.employeemanagement.Protos.Employee buildPartial() {
        com.tedsilb.employeemanagement.Protos.Employee result = new com.tedsilb.employeemanagement.Protos.Employee(this);
        result.id_ = id_;
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tedsilb.employeemanagement.Protos.Employee) {
          return mergeFrom((com.tedsilb.employeemanagement.Protos.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tedsilb.employeemanagement.Protos.Employee other) {
        if (other == com.tedsilb.employeemanagement.Protos.Employee.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tedsilb.employeemanagement.Protos.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tedsilb.employeemanagement.Protos.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * employees/{id}, id.length 10, [A-Za-z]
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * employees/{id}, id.length 10, [A-Za-z]
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * employees/{id}, id.length 10, [A-Za-z]
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * employees/{id}, id.length 10, [A-Za-z]
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * employees/{id}, id.length 10, [A-Za-z]
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.tedsilb.employeemanagement.Protos.Name name_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tedsilb.employeemanagement.Protos.Name, com.tedsilb.employeemanagement.Protos.Name.Builder, com.tedsilb.employeemanagement.Protos.NameOrBuilder> nameBuilder_;
      /**
       * <code>.Name name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return nameBuilder_ != null || name_ != null;
      }
      /**
       * <code>.Name name = 2;</code>
       * @return The name.
       */
      public com.tedsilb.employeemanagement.Protos.Name getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? com.tedsilb.employeemanagement.Protos.Name.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <code>.Name name = 2;</code>
       */
      public Builder setName(com.tedsilb.employeemanagement.Protos.Name value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Name name = 2;</code>
       */
      public Builder setName(
          com.tedsilb.employeemanagement.Protos.Name.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Name name = 2;</code>
       */
      public Builder mergeName(com.tedsilb.employeemanagement.Protos.Name value) {
        if (nameBuilder_ == null) {
          if (name_ != null) {
            name_ =
              com.tedsilb.employeemanagement.Protos.Name.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Name name = 2;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = null;
          onChanged();
        } else {
          name_ = null;
          nameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Name name = 2;</code>
       */
      public com.tedsilb.employeemanagement.Protos.Name.Builder getNameBuilder() {
        
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.Name name = 2;</code>
       */
      public com.tedsilb.employeemanagement.Protos.NameOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              com.tedsilb.employeemanagement.Protos.Name.getDefaultInstance() : name_;
        }
      }
      /**
       * <code>.Name name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tedsilb.employeemanagement.Protos.Name, com.tedsilb.employeemanagement.Protos.Name.Builder, com.tedsilb.employeemanagement.Protos.NameOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tedsilb.employeemanagement.Protos.Name, com.tedsilb.employeemanagement.Protos.Name.Builder, com.tedsilb.employeemanagement.Protos.NameOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final com.tedsilb.employeemanagement.Protos.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tedsilb.employeemanagement.Protos.Employee();
    }

    public static com.tedsilb.employeemanagement.Protos.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tedsilb.employeemanagement.Protos.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Name_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Name_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\"3\n\004Name\022\r\n\005first\030\001 \001(\t\022" +
      "\016\n\006middle\030\002 \001(\t\022\014\n\004last\030\003 \001(\t\"+\n\010Employe" +
      "e\022\n\n\002id\030\001 \001(\t\022\023\n\004name\030\002 \001(\0132\005.NameB*\n\036co" +
      "m.tedsilb.employeemanagementB\006ProtosH\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Name_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Name_descriptor,
        new java.lang.String[] { "First", "Middle", "Last", });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
